### ISSUE TITLE
[QST] `Cutlass / CuTe`

### ISSUE THREAD

**Issue by jeromeku** [andylolu2/cuda-nn#1]
@andylolu2 

Great work!  Learned a lot reading through your clean, well-designed code.

Any resources you'd recommend on getting a better grasp on `Cutlass / CuTe` usage patterns (other than the docs and `CuTe` tutorial)?  I've gone through the docs a few times but don't have a handle on how to effectively leverage the broad surface of its API.

**Comment by andylolu2** [comment]
Many thanks! It's unfortunately quite a struggle to write efficient-but-readable code in CUDA (e.g., I didn't implement vectorised loads for element-wise ops because it's going to make the code uglier.)

If you are interested in writing highly efficient code (and thus willing to sacrifice some readability) I find the flash-attention repository to be quite well-written.

**Comment by jeromeku** [comment]
Agree.  

I think one of the premises of `Cutlass` is to introduce abstractions that make it easier to write high(er) level CUDA code that still dispatches to efficient machine-level implementations, but I've been wrestling a bit with how to piece all these abstractions together.  Chalk it up to opacity on my part :)  

OpenAI's `triton` is another great library that further abstracts kernel implementations to a Pythonic DSL that generates highly efficient backend-agnostic code through a ML-specific compilation pipeline.  Naturally both `triton`'s compilation pipeline and `Cutlass` overlap a bit in terms of the abstractions introduced -- i.e., the GEMM hierarchy, data layouts, etc. -- and it's been helpful to learn both approaches.
